#!/bin/sh
# gen-codeowners.test.sh: tests for scripts/gen-codeowners.sh.
#
# Usage: sh tests/gen-codeowners.test.sh
#
# Builds throwaway repositories in a temporary directory, runs the generator
# in each, and checks the exit code, the message and the file written. Prints
# one TAP-style line per case and exits 1 if any case fails. Needs git;
# touches nothing outside the temporary directory.
#
# SC2016: the backticks in single quotes are Markdown, not substitutions.
# SC2319: each case passes the exit status of its condition on purpose.
# shellcheck disable=SC2016,SC2319

set -u

here="$(cd "$(dirname "$0")/.." && pwd)"
gen="$here/scripts/gen-codeowners.sh"

command -v git >/dev/null 2>&1 || { printf 'Bail out! git not found\n'; exit 1; }

T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT INT TERM

n=0
failed=0
result() { # result <ok 0|1> <label> [detail]
  n=$((n + 1))
  if [ "$1" = 0 ]; then
    printf 'ok %d - %s\n' "$n" "$2"
  else
    printf 'not ok %d - %s\n' "$n" "$2"
    [ -n "${3:-}" ] && printf '%s\n' "$3" | sed 's/^/# /'
    failed=$((failed + 1))
  fi
}

# mkrepo <name> [origin url]: the default origin is an ssh github.com URL.
mkrepo() {
  git init -q -b main "$T/$1"
  mkdir -p "$T/$1/product"
  [ "${2-x}" = none ] || git -C "$T/$1" remote add origin "${2:-git@github.com:blairforce1/$1.git}"
}
commit() {
  git -C "$T/$1" add -A
  git -C "$T/$1" -c user.name=test -c user.email=test@example.invalid \
    -c commit.gpgsign=false commit -q -m "${2:-x}"
}

# The envision template's section, plus a duplicate, a star bullet and a
# backticked word in the prose line, which is not a bullet and is ignored.
sample='# Invariants: sample

## Security posture
- **INV-001** Secrets never leave `vault/`.

## Protected paths
No agent may change these without a human approval recorded on the `change`.
- `migrations/**`
- `infra/**`
- `**/*.test.*` and `tests/**`
- `product/**`
- `CLAUDE.md`, `REVIEW.md`, `.claude/**`
* `/docs/adr/` (records)
- `infra/**`

## Open questions
- `not/protected/**`: candidate only.'

expected='# Generated by scripts/gen-codeowners.sh from the "Protected paths" section
# of product/invariants.md. Do not edit by hand: change product/invariants.md and
# run scripts/gen-codeowners.sh.

/migrations/** @blairforce1
/infra/** @blairforce1
**/*.test.* @blairforce1
/tests/** @blairforce1
/product/** @blairforce1
/CLAUDE.md @blairforce1
/REVIEW.md @blairforce1
/.claude/** @blairforce1
/docs/adr/ @blairforce1'

# A sample invariants.md produces the expected file.
mkrepo sample
printf '%s\n' "$sample" > "$T/sample/product/invariants.md"
out="$(cd "$T/sample/product" && sh "$gen" 2>&1)"
rc=$?
got="$(cat "$T/sample/.github/CODEOWNERS" 2>/dev/null)"
[ "$rc" = 0 ] && [ "$got" = "$expected" ]
result $? 'sample invariants.md writes the expected .github/CODEOWNERS, owner from an ssh origin, run from a subdirectory' \
  "exit $rc; $out
$(printf '%s\n' "$expected" > "$T/want"; printf '%s\n' "$got" | diff -u "$T/want" - )"

# `-` writes the same content to stdout and nothing to disk.
mkrepo stdout
printf '%s\n' "$sample" > "$T/stdout/product/invariants.md"
got="$(cd "$T/stdout" && sh "$gen" -)"
[ "$got" = "$expected" ] && [ ! -e "$T/stdout/.github" ]
result $? "'-' writes to stdout only"

# Idempotence: a second run leaves the committed file unchanged.
commit sample init
(cd "$T/sample" && sh "$gen") >/dev/null 2>&1
rc=$?
st="$(git -C "$T/sample" status --porcelain)"
[ "$rc" = 0 ] && [ -z "$st" ]
result $? 'second run produces no diff' "exit $rc; status: $st"

# Absent file.
mkrepo nofile
out="$(cd "$T/nofile" && sh "$gen" 2>&1)"
rc=$?
[ "$rc" = 1 ] && [ "$out" = 'gen-codeowners: product/invariants.md not found' ] \
  && [ ! -e "$T/nofile/.github" ]
result $? 'absent product/invariants.md exits 1 naming the file' "exit $rc; $out"

# Absent section.
mkrepo nosection
printf '# Invariants\n\n## Security posture\n- `vault/**`\n' > "$T/nosection/product/invariants.md"
out="$(cd "$T/nosection" && sh "$gen" 2>&1)"
rc=$?
[ "$rc" = 1 ] \
  && [ "$out" = "gen-codeowners: no '## Protected paths' section in product/invariants.md" ] \
  && [ ! -e "$T/nosection/.github" ]
result $? 'absent Protected paths section exits 1 naming the section' "exit $rc; $out"

# A section with no paths, and a path CODEOWNERS cannot express.
mkrepo empty
printf '## Protected paths\nNone yet.\n' > "$T/empty/product/invariants.md"
out="$(cd "$T/empty" && sh "$gen" 2>&1)"
rc=$?
[ "$rc" = 1 ] && [ ! -e "$T/empty/.github" ]
result $? 'section with no paths exits 1' "exit $rc; $out"

mkrepo negated
printf '## Protected paths\n- `infra/**`\n- `!infra/README.md`\n' > "$T/negated/product/invariants.md"
out="$(cd "$T/negated" && sh "$gen" 2>&1)"
rc=$?
[ "$rc" = 1 ] && [ ! -e "$T/negated/.github" ]
result $? 'negated path exits 1 and writes nothing' "exit $rc; $out"

# Owner: https origin, the flag over the origin, the flag with no origin,
# and neither.
two='## Protected paths
- `infra/**`'
mkrepo https https://someone@github.com/Some-Org/repo.git
printf '%s\n' "$two" > "$T/https/product/invariants.md"
got="$(cd "$T/https" && sh "$gen" - | tail -n 1)"
[ "$got" = '/infra/** @Some-Org' ]
result $? 'owner from an https origin with a user part' "got: $got"

mkrepo sshurl ssh://git@github.com/Other/repo
printf '%s\n' "$two" > "$T/sshurl/product/invariants.md"
got="$(cd "$T/sshurl" && sh "$gen" - | tail -n 1)"
[ "$got" = '/infra/** @Other' ]
result $? 'owner from an ssh:// origin without .git' "got: $got"

got="$(cd "$T/https" && sh "$gen" --owner @team-x - | tail -n 1)"
[ "$got" = '/infra/** @team-x' ]
result $? '--owner overrides the origin' "got: $got"

mkrepo noorigin none
printf '%s\n' "$two" > "$T/noorigin/product/invariants.md"
got="$(cd "$T/noorigin" && sh "$gen" --owner=bob - | tail -n 1)"
[ "$got" = '/infra/** @bob' ]
result $? '--owner=<owner> with no origin, @ added' "got: $got"

out="$(cd "$T/noorigin" && sh "$gen" 2>&1)"
rc=$?
[ "$rc" = 1 ] \
  && [ "$out" = 'gen-codeowners: no owner: pass --owner <owner>, or set an origin remote on github.com/<owner>/<repo>' ] \
  && [ ! -e "$T/noorigin/.github" ]
result $? 'no origin and no --owner exits 1 naming both' "exit $rc; $out"

mkrepo gitlab git@gitlab.com:someone/repo.git
printf '%s\n' "$two" > "$T/gitlab/product/invariants.md"
out="$(cd "$T/gitlab" && sh "$gen" 2>&1)"
rc=$?
[ "$rc" = 1 ] && [ ! -e "$T/gitlab/.github" ]
result $? 'an origin not on github.com is not an owner' "exit $rc; $out"

# --check compares against the index: fresh passes, a changed invariants.md
# fails, a regenerated but unstaged file still fails, staging it passes.
mkrepo check
printf '%s\n' "$two" > "$T/check/product/invariants.md"
(cd "$T/check" && sh "$gen") && commit check
(cd "$T/check" && sh "$gen" --check) >/dev/null 2>&1
result $? '--check passes when the index copy is current'

printf -- '- `migrations/**`\n' >> "$T/check/product/invariants.md"
out="$(cd "$T/check" && sh "$gen" --check 2>&1)"
rc=$?
[ "$rc" = 1 ] && [ "$out" = 'gen-codeowners: .github/CODEOWNERS is stale for product/invariants.md; run scripts/gen-codeowners.sh and git add .github/CODEOWNERS' ]
result $? '--check fails when invariants.md changed' "exit $rc; $out"

(cd "$T/check" && sh "$gen")
(cd "$T/check" && sh "$gen" --check) >/dev/null 2>&1
[ $? = 1 ]
result $? '--check fails when the regenerated file is not staged'

git -C "$T/check" add .github/CODEOWNERS
(cd "$T/check" && sh "$gen" --check) >/dev/null 2>&1
result $? '--check passes once the regenerated file is staged'

mkrepo checknew
printf '%s\n' "$two" > "$T/checknew/product/invariants.md"
out="$(cd "$T/checknew" && sh "$gen" --check 2>&1)"
rc=$?
[ "$rc" = 1 ] && [ ! -e "$T/checknew/.github" ]
result $? '--check fails with no CODEOWNERS in the index, and writes nothing' "exit $rc; $out"

printf '1..%d\n' "$n"
[ "$failed" = 0 ] || { printf '# %d of %d failed\n' "$failed" "$n"; exit 1; }
