#!/bin/sh
# gen-codeowners.sh: writes .github/CODEOWNERS from the "Protected paths"
# section of product/invariants.md, so the paths no agent may change without
# a recorded human approval (process section 3.2) are the paths GitHub and
# the pr-checks workflow treat as protected.
#
# Usage: gen-codeowners.sh [output]
#
#   output  Where to write, relative to the repository root. Default
#           .github/CODEOWNERS; `-` writes to stdout, which is how
#           `mise run check:codeowners` compares without writing.
#
# Every backticked path on a bullet line of the section becomes one line
# owned by $owner. A path that does not start with `/` or `**` is anchored at
# the root with a leading `/`: invariants.md means the repository's
# CLAUDE.md, not every CLAUDE.md. CODEOWNERS has no negation or character
# ranges, so a path with `!`, `[` or whitespace is refused.
#
# Exits 1 with one line on stderr when the file, the section or its paths
# are missing. Running it twice produces the same file.

set -eu

owner='@blairforce1'
src='product/invariants.md'

die() {
  printf 'gen-codeowners: %s\n' "$1" >&2
  exit 1
}

root="$(git rev-parse --show-toplevel 2>/dev/null)" || die 'not inside a git repository'
cd "$root"
out="${1:-.github/CODEOWNERS}"

[ -f "$src" ] || die "$src not found"
grep -q '^## Protected paths[[:space:]]*$' "$src" \
  || die "no '## Protected paths' section in $src"

paths="$(awk '
  /^## / { inside = ($0 ~ /^## Protected paths[[:space:]]*$/); next }
  inside && /^[[:space:]]*[-*] / {
    line = $0
    while (match(line, /`[^`]+`/)) {
      print substr(line, RSTART + 1, RLENGTH - 2)
      line = substr(line, RSTART + RLENGTH)
    }
  }' "$src" | awk '!seen[$0]++')"

[ -n "$paths" ] || die "no backticked paths under '## Protected paths' in $src"

body="$(printf '%s\n' "$paths" | while IFS= read -r p; do
  case "$p" in
    '!'* | *'['* | *[[:space:]]*) die "cannot express '$p' in CODEOWNERS" ;;
    /* | '**'*) ;;
    *) p="/$p" ;;
  esac
  printf '%s %s\n' "$p" "$owner"
done)" || exit 1

content="$(printf '%s\n' \
  '# Generated by scripts/gen-codeowners.sh from the "Protected paths" section' \
  "# of $src. Do not edit by hand: change $src and" \
  '# run scripts/gen-codeowners.sh.' \
  '' \
  "$body")"

if [ "$out" = - ]; then
  printf '%s\n' "$content"
else
  mkdir -p "$(dirname "$out")"
  printf '%s\n' "$content" > "$out"
fi
