// sonar-suggestions.cs: prints the .globalconfig block that sets every
// default-on SonarAnalyzer.CSharp rule's severity by its Sonar rule type:
// Bug and Vulnerability at warning, which TreatWarningsAsErrors makes a
// build failure; Code Smell and Security Hotspot at suggestion. A rule
// with no type (Sonar's internal metric generators) is a suggestion.
//
// The rule list comes from the analyzer DLL. The type does not: the DLL's
// diagnostic category calls a hotspot a Vulnerability, so the type is read
// from Sonar's rspec metadata, analyzers/rspec/cs/<id>.json in
// SonarSource/sonar-dotnet, at the tag equal to the DLL's file version.
// Needs network. Run it after a SonarAnalyzer.CSharp version bump and
// replace the block in templates/dotnet/.globalconfig with its output:
//
//   dotnet run scripts/sonar-suggestions.cs -- \
//     ~/.nuget/packages/sonaranalyzer.csharp/<version>/analyzers/SonarAnalyzer.CSharp.dll
#:package Microsoft.CodeAnalysis.CSharp@4.14.0
#:property PublishAot=false

using System.Diagnostics;
using System.Net;
using System.Reflection;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;

if (args.Length != 1)
{
    Console.Error.WriteLine("usage: dotnet run scripts/sonar-suggestions.cs -- <SonarAnalyzer.CSharp.dll>");
    return 1;
}

var version = FileVersionInfo.GetVersionInfo(args[0]).FileVersion
    ?? throw new InvalidOperationException("the DLL has no file version");

Type[] types;
try
{
    types = Assembly.LoadFrom(args[0]).GetTypes();
}
catch (ReflectionTypeLoadException ex)
{
    // The code fixes need Microsoft.CodeAnalysis.Workspaces, which is not
    // referenced here; the analyzers load without it.
    types = [.. ex.Types.OfType<Type>()];
}

var ids = new SortedSet<string>(StringComparer.Ordinal);
foreach (var type in types.Where(t => !t.IsAbstract && typeof(DiagnosticAnalyzer).IsAssignableFrom(t)))
{
    if (type.GetConstructor(Type.EmptyTypes) is null)
    {
        continue;
    }
    var analyzer = (DiagnosticAnalyzer)Activator.CreateInstance(type)!;
    foreach (var d in analyzer.SupportedDiagnostics)
    {
        if (d.IsEnabledByDefault && d.DefaultSeverity >= DiagnosticSeverity.Warning)
        {
            ids.Add(d.Id);
        }
    }
}

// id -> rspec type. A 404 is a rule with no rspec file; anything else fails.
using var http = new HttpClient();
var baseUri = $"https://raw.githubusercontent.com/SonarSource/sonar-dotnet/{version}/analyzers/rspec/cs/";
var typeOf = new Dictionary<string, string>(StringComparer.Ordinal);
await Parallel.ForEachAsync(ids, new ParallelOptions { MaxDegreeOfParallelism = 16 }, async (id, ct) =>
{
    using var response = await http.GetAsync(baseUri + id + ".json", ct);
    if (response.StatusCode == HttpStatusCode.NotFound)
    {
        return;
    }
    response.EnsureSuccessStatusCode();
    using var json = JsonDocument.Parse(await response.Content.ReadAsStringAsync(ct));
    var ruleType = json.RootElement.GetProperty("type").GetString()!;
    lock (typeOf)
    {
        typeOf[id] = ruleType;
    }
});

(string Type, string Label, string Severity)[] groups =
[
    ("BUG", "Bug", "warning"),
    ("VULNERABILITY", "Vulnerability", "warning"),
    ("CODE_SMELL", "Code Smell", "suggestion"),
    ("SECURITY_HOTSPOT", "Security Hotspot", "suggestion"),
    ("", "No type (internal metric generators)", "suggestion"),
];
var unknown = typeOf.Values.Distinct().Where(t => groups.All(g => g.Type != t)).ToList();
if (unknown.Count > 0)
{
    Console.Error.WriteLine($"unknown rule types: {string.Join(", ", unknown)}; add them to the groups");
    return 1;
}

Console.WriteLine($"# Generated by scripts/sonar-suggestions.cs from SonarAnalyzer.CSharp {version}.");
foreach (var (ruleType, label, severity) in groups)
{
    var members = ids.Where(id => typeOf.GetValueOrDefault(id, "") == ruleType).ToList();
    Console.WriteLine();
    Console.WriteLine($"# {label}: {members.Count} rules at {severity}");
    foreach (var id in members)
    {
        Console.WriteLine($"dotnet_diagnostic.{id}.severity = {severity}");
    }
    Console.Error.WriteLine($"{label}: {members.Count}");
}
return 0;
